# config.yaml
paths:
  base_dir: "."
  db_images: "database_images"
  db_pkl_folder: "database"
  models_folder: "models"

artifacts:
  pack_vec: "database/pill_fingerprints.pkl" 
  pack_col: "database/colors_packs.pkl"
  model: "models/seg_best_process.pt"

settings:
  dino_size: 336
  yolo_conf: 0.8